print ("Exercícios")
print ("Qual é o output do seguinte snippet?")
print ('String Multiplicada: x * "5"')
x = int(input("Enter a number: ")) # The user enters 2
print(x * "5")
print ("------------------------------------------------")
print ("123 + 0.0 is:")
print (123 + 0.0)
print ("------------------------------------------------")
print ("Como fica: 1 ** 2 ** 3")
print (1 ** 2 ** 3)
print ("------------------------------------------------")
print ("Qual o resultado de: 1 // 2 * 3 ")
print ( 1 // 2 * 3 )
print ("------------------------------------------------")
print ("Some 2 numeros")
x = int(input("Enter a number: "))
y = int(input("Enter a number: "))

print ("SOMA: ", x + y)
